name: client
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_datetime_picker: ^1.5.1
  flutter_typeahead: ^4.6.1
  http: ^0.13.4
  cloud_firestore: ^4.8.0
  firebase_auth: ^4.6.2
  firebase_core: ^2.13.1
  flutter_lints: ^2.0.0
  shared_preferences: ^2.1.1
  flutter_rating_bar: ^4.0.1
  font_awesome_flutter: ^10.4.0
  bottom_navy_bar: ^6.0.0
  carousel_slider: ^4.2.1
  flutter_svg: ^2.0.6
  firebase_database: ^10.2.2
  intl: ^0.17.0
  permission_handler: ^10.3.0
  firebase_storage: ^11.2.2
  google_sign_in: ^6.1.4
  iconly: ^1.0.1
  cloudinary_flutter: ^0.9.0
  flutter_webrtc: ^0.9.33
  image_picker: ^0.8.8
  dio: ^5.2.1+1
  lottie: ^1.2.0
  simple_animations: ^5.0.2
  flutter_dotenv: ^5.1.0
  flutter_stripe: ^9.2.2
  get: ^4.6.5

  curved_navigation_bar: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/icons/
    - assets/images/
  uses-material-design: true
